-- Icon for control victory
-- use repair walls for now

INSERT INTO IconDefinitions (Name, Atlas, 'Index') VALUES
('ICON_PROJECT_SHOW_SUPERIORITY_SAM', 'ICON_ATLAS_PROJECTS', 0),
('PROJECT_SHOW_SUPERIORITY_SAM', 'ICON_ATLAS_PROJECTS', 0),
('ICON_PROJECT_EXERT_INFLUENCE_SAM', 'ICON_ATLAS_PROJECTS', 0)
('PROJECT_EXERT_INFLUENCE_SAM', 'ICON_ATLAS_PROJECTS', 0);