-- Create all necessary table insertions to add the capture zone resource

INSERT INTO Types (Type, Kind) VALUES 
('RESOURCE_VICTORY_POINTS_SAM', 'KIND_RESOURCE');

INSERT INTO TypeTags (Type, Tag) VALUES 
('RESOURCE_VICTORY_POINTS_SAM', 'CLASS_PRODUCTION'),
('RESOURCE_VICTORY_POINTS_SAM', 'CLASS_SCIENCE'),
('RESOURCE_VICTORY_POINTS_SAM', 'CLASS_CULTURE');

INSERT INTO Resources (ResourceType, Name, ResourceClassType, Frequency) VALUES
('RESOURCE_VICTORY_POINTS_SAM', 'LOC_RESOURCE_VICTORY_POINTS_SAM_NAME', 'RESOURCECLASS_STRATEGIC', 0);

INSERT INTO Resource_YieldChanges (ResourceType, YieldType, YieldChange) VALUES
('RESOURCE_VICTORY_POINTS_SAM', 'YIELD_PRODUCTION', 2),
('RESOURCE_VICTORY_POINTS_SAM', 'YIELD_SCIENCE', 2),
('RESOURCE_VICTORY_POINTS_SAM', 'YIELD_CULTURE', 2);

INSERT INTO Resource_Consumption (ResourceType, Accumulate, BaseExtractionRate, ImprovedExtractionRate, StockpileCap) VALUES
('RESOURCE_VICTORY_POINTS_SAM', 1, 0, 1, 1000);