-- Capture zone victory

INSERT INTO Types (Type, Kind) VALUES
('VICTORY_CAPTURE_SAM', 'KIND_VICTORY');

INSERT INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES
('REQUIREMENTS_CAPTURE_VICTORY_SAM', 'REQUIREMENTSET_TEST_ALL');

INSERT INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES
('REQUIREMENTS_CAPTURE_VICTORY_SAM', 'REQUIRES_NOTHING');

INSERT INTO Victories (VictoryType, Name, Blurb, RequirementSetId) VALUES
('VICTORY_CAPTURE_SAM', 'LOC_VICTORY_CAPTURE_SAM_NAME', 'LOC_VICTORY_CAPTURE_SAM_TEXT', 'REQUIREMENTS_CAPTURE_VICTORY_SAM');